### ISSUE TITLE
why is my app grayed out?

### ISSUE THREAD

**Issue by ndimhypervol** [rstudio/shinyapps#133]
When I publish, my app is grayed out and not functional. Why might this be?

**Comment by CBarraford** [comment]
the app could be crashing. Checkout your logs.

```
shinyapps::showLogs()
```

**Comment by ndimhypervol** [comment]
Got it. I was trying to install packages, and it errored. I didn't see anything in reference to this in the tutorial, and it might be useful to warn users to remove these commands before they publish. Thanks.

**Comment by cmohamma** [comment]
I have this sam issue, the logs say 

shinyapps::showLogs()
Error in loadNamespace(name) : there is no package called ‘shiny apps’


I have NO IDEA why i'm getting this, any thoughts?

Here's my app on github
https://github.com/cmohamma/lebanon

**Comment by kippandrew** [comment]
It sounds like you might have a typo in your app. `shinyapps` is package name, and it should be one word.

**Comment by rpbscott** [comment]
I have the same problem, but no errors are outputted when I run shinyapps::showLogs()...(see [this stackoverflow post] (http://stackoverflow.com/questions/34841795/rs-shiny-app-goes-grey-when-deployed-works-fine-locally for the full output) ). I've also tried increasing the size of the application instance and decreasing the number of workers per application instance as is recommend [here]  (http://shiny.rstudio.com/articles/scaling-and-tuning.html) I have a feeling memory usage isn't the problem because one of my apps is extremely simple and the calculations it makes are done within a second or two when run locally. I've also checked out the memory usage of the apps on the shiny dashboard and the usage is no where near the memory limit.

Any help is GREATLY appreciated. [Here's] (https://rosemarie-p-b-scott.shinyapps.io/OM_2266/) an example of one of the problematic shiny apps. This one takes a bit longer to turn grey.
