### ISSUE TITLE
Accessing a file on the shinyapps.io server

### ISSUE THREAD

**Issue by niklasvm** [rstudio/shinyapps#205]
My shiny app that's hosted on shinyapps.io writes data to a sqlite database. Is it possible to download a copy of the sqlite file in order to troubleshoot?

**Comment by kippandrew** [comment]
You could use a `downloadHandler()` to download the file from the within shiny application itself. Otherwise its not currently possible to access the data written to the disk. Also, keep in mind that data written will be removed when the application goes to sleep, and start fresh after it is resumed. You may want to consider saving the data to a remote location (perhaps Dropbox or S3) if thats important.
